<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Bloat.Web</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\Bloat.Core\Bloat.Core.csproj" />
  </ItemGroup>

</Project>
