<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bloat.Core\Bloat.Core.csproj" />
    <ProjectReference Include="..\Bloat.Web\Bloat.Web.vbproj" />
  </ItemGroup>

</Project>
